name: GitHub Pages

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: corepack enable
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 21
          cache: yarn

      - run: yarn install --immutable
      - run: yarn workspace app build
      - name: Upload pages artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v2
        with:
          path: packages/app/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3